[package]
name = "tilemap-atlas"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/Tilemap"
documentation = "https://docs.rs/tilemap"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
image = "0.24.6"

[dev-dependencies]

[features]
default = []
