[workspace]
members = ["projects/*"]
default-members = [
    "projects/tilemap",
    "projects/tilemap-atlas",
    "projects/tilemap-auto",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
